spring.application.name=worksphere-api

spring.datasource.url = jdbc:postgresql://localhost:5432/worksphere
spring.datasource.username = postgres
spring.datasource.password = Your_Password
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port=8080

jwt.secret = Your_Secret
jwt.expiration = 86400000