spring.application.name=worksphere-api

spring.datasource.url = jdbc:postgresql://localhost:5432/worksphere
spring.datasource.username = postgres
spring.datasource.password = 0000
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port=8080

jwt.secret = worksphere-jwt-secret-key-1234567890-worksphere-jwt
jwt.expiration = 86400000